######## Start a new stage from scratch #######
FROM alpine:latest

# RUN apk --no-cache add ca-certificates

WORKDIR /root/

# RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

# Copy the Pre-built binary file from the previous stage
COPY . .

# Command to run the executable
# CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
CMD exec /bin/sh -c "trap : TERM INT; (while true; do sleep 1000; done) & wait"